### ISSUE TITLE
Add OS X support (Pod specs)

### ISSUE THREAD

**Issue by torcelly** [kevintuhumury/itvdb#12]
Hi,

First of all, congratulation for your work. Great library.

Could you add support OS X in the pod specs? Maybe I'm wrong, but I believe itvdb doesn't use any exclusive iOS library. 

Thanks!

**Comment by kevintuhumury** [comment]
Hi @torcelly, it took me a while to respond to your message, since I didn't get a notification of this issue at all (or I've somehow overlooked it). OSX support has been added by @jbmorley and I've just added it to iTVDb and even submitted it to Cocoapods, see [iTVDb v0.0.5](https://github.com/CocoaPods/Specs/blob/master/Specs/iTVDb/0.0.5/iTVDb.podspec.json).

**Comment by torcelly** [comment]
Great!! Thanks Kevin.
